http:
  routers:
    blog:
      entryPoints:
        - "https"
        - "http"
      rule: "Host(`freelancingspot.com`) || Host(`www.freelancingspot.com`)"
      service: blog_service
      tls: {}
      middlewares:
        - https-redirect-scheme
        - default-headers

    portainer:
      entryPoints:
        - "https"
      rule: "Host(`portainer.freelancingspot.com`)"
      service: portainer_service
      tls: {}
      middlewares:
        - https-redirect-scheme
        - default-headers
  services:
    blog_service:
      loadBalancer:
        servers:
          - url: "http://ghost:2368/"
        passHostHeader: true
    
    portainer_service:
      loadBalancer:
        servers:
          - url: "https://10.218.0.2:9443/"
        passHostHeader: true



  middlewares:
    https-redirect-scheme:
      redirectScheme:
        scheme: https
        permanent: true
    default-headers:
      headers:
        frameDeny: true
        browserXssFilter: true
        contentTypeNosniff: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 15552000
        customFrameOptionsValue: SAMEORIGIN
        customRequestHeaders:
          X-Forwarded-Proto: https
    idrac:
      headers:
        frameDeny: true
        browserXssFilter: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsSeconds: 15552000
        customFrameOptionsValue: SAMEORIGIN
        customRequestHeaders:
          X-Forwarded-Proto: https

    default-whitelist:
      ipWhiteList:
        sourceRange:
        - "10.0.0.0/8"
        - "192.168.0.0/16"
        - "172.16.0.0/12"

    secured:
      chain:
        middlewares:
        - default-whitelist
        - default-headers

    helpdesk_redirect:
      redirectregex:
        regex: ^/$"
        replacement: /knowledge_center
 


    assets_compress:
      compress: true