version: '2'
services:
  caddy:
    # image: caddy:2
    build: .
    restart: unless-stopped
    networks:
      - ghost_nw
    environment:
      - CF_DNS_API_TOKEN=AHSOtsBolgvFp0jxZpWae6iUiPou947MUEd_hBBi # brian
      # - CF_DNS_API_TOKEN=QbfvWvPPopGOzdJivhDd4zv3zfo-t4MSnN_Y-WxN  # vincent
      - CF_API_TOKEN=AHSOtsBolgvFp0jxZpWae6iUiPou947MUEd_hBBi # brian
      # - CF_API_TOKEN=QbfvWvPPopGOzdJivhDd4zv3zfo-t4MSnN_Y-WxN  #vincent
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # - $PWD/Caddyfile_vincent:/etc/caddy/Caddyfile #vincent
      - $PWD/Caddyfile:/etc/caddy/Caddyfile #brain
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - ghost
  ghost:     
    image: ghost:latest
    container_name: ghost
    hostname: ghost
    volumes:
      - $(PWD)/configproductionbrain.json:/var/lib/ghost/config.production.json:z
      - blog_ghost_content:/var/lib/ghost/content
    ports:
      - "2368:2368"
    environment: 
      NODE_ENV: production
      url: https://freelancingspot.com
      admin__url: https://freelancingspot.com
      # url: https://cryptotradinginfo.com
      # admin__url: https://cryptotradinginfo.com
      database__client: mysql
      database__connection__host: mysql
      database__connection__user: itara
      database__connection__port: 3306
      database__connection__password: abcd@123
      database__connection__database: ghostdata
    restart: always
    links:
      - mysql
    networks:
      - ghost_nw
      - mysql_nw
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: mysql
    volumes:
       - blog_ghost_database:/var/lib/mysql:z
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=abcd@123
      - MYSQL_DATABASE=ghostdata
      - MYSQL_USER=itara
      - MYSQL_PASSWORD=abcd@123
    restart: always
    networks:
      - mysql_nw


volumes:
  blog_ghost_content:
    external: true
  blog_ghost_database:
    external: true
  caddy_data:
  caddy_config:
networks:
  ghost_nw:
  mysql_nw:


